#!/bin/sh
#Usage: ./ssh_general_script input_file execution_file
VOLUME_BRICK_DIRECTORY="$HOME/gluster_s0058_brick"
CLIENT_DIRECTORY="$HOME/gluster_client/"
declare err=0;
fs_nodes=( umu3 umu12 )
declare -A fs_nodes_hash
for constant in "${fs_nodes[@]}"; do
    fs_nodes_hash[$constant]=1
done

#---------------------------------------------------------------
#	Setting glusterfs up region
#---------------------------------------------------------------

if [[ ${fs_nodes_hash[$SLURMD_NODENAME]} ]]; then       # if it is FS clusters
     sudo mkdir "$VOLUME_BRICK_DIRECTORY"
	 echo "Create dir code is $?"

#--------------------------------------------------------------
#	Giving task for calculating nodes and observing
#-------------------------------------------------------------

	INPUT_FILE="$1";
	OUTPUT_FILE="out"
	files=( umu1 umu2 );
	count=${#files[@]};
	condition="";

	for i in "${files[@]}"; do
        	condition=${condition}" [ -f "$i.out" ] &&";
	done;
	condition=${condition}" break";

	while true; do
	        sleep 20;
	        eval "$condition";
	done;   

#----------------------------------------------------------------------
#	Region of terninating sshfs and removing temp files
#----------------------------------------------------------------------

    sudo rm -r "$VOLUME_BRICK_DIRECTORY"
        
#-----------------------------------------------------------------------
#	Region for calculating nodes
#-----------------------------------------------------------------------

else
	err=1;
	condition="";
	for node in "${fs_nodes[@]}"; do
		condition=${condition}"sshfs $node:$VOLUME_BRICK_DIRECTORY $CLIENT_DIRECTORY\n";
	done
	
	for i in {1..5}; do
		eval "$condition"
		err="$?";
		[ "$err" == "0" ] && break;
		sleep 5;
	done;
	[ "$err" != "0" ] && exit;	# не смогли примонтировать - выходим

	eval "$2"
	touch "$SLURMD_NODENAME.out"
fi

